name = "hard-spheres-mixing"
version = "0.1.0"
license = "license"
author = "F.E. Benelli & F.A. Sanchez"
maintainer = "federico.benelli@mi.unc.edu.ar"
copyright = "Copyright 2023, Federico E. Benelli"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
